version: '3.8'

services:
  wulong:
    image: julienberanger/wulong:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - KMS_URL=${KMS_URL}
      - ADMIN_MLKEM_PUBLIC_KEY=${ADMIN_MLKEM_PUBLIC_KEY}
      - ADMIN_MLKEM_PRIVATE_KEY=${ADMIN_MLKEM_PRIVATE_KEY}
    restart: unless-stopped
